spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kpsecdb
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  config: classpath:static/logback.xml